#!/usr/bin/env bash

set -eu

# git privacy - keep your coding hours private

read -d '' __post_commit << 'EOF' || true
#!/usr/bin/env bash

# git-privacy hook to redact
# set environment var GIT_PRIVACY_DISABLE to skip redacting.

set -e

. "$(pwd)/$(dirname "$0")"/git-privacy
privacy_redact
EOF

function privacy_init() {
  # creates the post-commit hook that redacts commit timestamps

  if [[ "$(git rev-parse --is-inside-work-tree)" != "true" ]]; then
    echo "git-privacy: not a git repo!"
    exit 1
  fi

  # copies git-privacy locally
  cp "$(which git-privacy)" .git/hooks/git-privacy

  # creates hook
  echo "$__post_commit" > .git/hooks/post-commit
  chmod +x .git/hooks/post-commit
}

function privacy_redact() {
  # redacts last commit HH:MM:SS+ZZZZ to 00:00:00+0000

  # avoid infinite commit loop / disable redacting
  [[ -z ${GIT_PRIVACY_DISABLE:-''} ]] || return

  # get author date
  author_old_date=$(git log --date=format:'%Y-%m-%d' --pretty=format:'%ad' -n1)

  # get committer date/time
  commit_old_date=$(git log --date=format:'%Y-%m-%d' --pretty=format:'%cd' -n1)
  # commit_old_time=$(git log --date=format:'%H:%M:%S' --pretty=format:'%cd' -n1)

  # stash changes (git commit --amend commits staged changes)
  pre_stash_size=$(git stash list | wc -l)
  git stash || true
  post_stash_size=$(git stash list | wc -l)

  # calculate new author/commit timestamp
  author_new_datetime="${author_old_date}T00:00:00+0000"
  commit_new_datetime="${commit_old_date}T00:00:00+0000"

  # amend commit
  GIT_PRIVACY_DISABLE=1 GIT_COMMITTER_DATE="$commit_new_datetime" \
    git commit \
    --amend --date="$author_new_datetime" --no-edit --no-verify --allow-empty

  # apply stash if any
  (( pre_stash_size != post_stash_size )) && git stash pop || true

  return
}
