#!/usr/bin/env bash

set -eu

# tests/utils - general test help functions

die() { echo "$*" 1>&2 ; exit 1; }

function _setup() {

  (( $# == 0 )) || (( $# == 1 )) || die "E: Usage: _setup 'folder_name' (got $#: $*)"

  folder_name=${1:-'playground'}

  rm -fr tests/$folder_name
  mkdir -p tests/$folder_name
  pushd tests/$folder_name > /dev/null || exit 1

  git init
}

function _teardown() {
  popd > /dev/null || exit 1
}

function assert() {

  (( $# == 2 )) || die "E: Usage: assert 'expected' 'actual' (got $#: $*)"

  local expected=$1
  local actual=$2

  if [[ "$expected" == "$actual" ]]; then
    echo OK
    exit 0
  else
    echo "expected: $expected"
    echo "actual  : $actual"
    exit 1
  fi
}

function commit_with_clear_timestamp() {
  # commit with non redacted timestamp

  GIT_AUTHOR_DATE=2025-05-05T05:05:05+0500 \
    GIT_COMMITTER_DATE=2026-06-06T06:06:06+0600 \
    git commit --allow-empty -m "${1:-old commit}"
}
