#!/usr/bin/env bash

set -eu

# tests/utils - general test help functions

die() { echo "$*" 1>&2 ; exit 1; }

function assert() {

  (( $# == 2 )) || die "E: Usage: assert 'expected' 'actual' (got $#: $*)"

  local expected=$1
  local actual=$2

  if [[ "$expected" == "$actual" ]]; then
    echo OK
    exit 0
  else
    echo "expected: $expected"
    echo "actual  : $actual"
    exit 1
  fi
}
